# Generated by Django 5.1.6 on 2025-02-28 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='realeae_year',
            new_name='release_year',
        ),
    ]
